version: '2.1'
services:
  web:
    image: nfqlt/ruby2
    network_mode: bridge
    ports:
      - '10.24.1.17:80:4000'
    volumes:
      - './src:/home/project/src'
      - /tmp


  dev:
    image: nfqlt/php70-dev
    network_mode: bridge
    ports:
      - '10.24.1.17:22:22'
    volumes_from:
      - service:web:rw
    volumes:
      - './src:/home/project/src'
      - '/home/project/.ssh:/home/project/.ssh'
      - '/etc/ssh:/etc/ssh'
      - '/etc/gitconfig:/etc/gitconfig'
      - '/etc/environment:/etc/environment-vm:ro'
      - '/vagrant/bash_custom:/home/project/.bash_custom'
    environment:
      NFQ_PROJECT_ROOT: /home/project/src
      NFQ_PROJECT_GIT_REPO: 'https://github.com/makerspacelt/makerspacelt.github.io.git'
      NFQ_PROJECT_GIT_BRANCH: master
      NFQ_INIT_SCRIPT: tools/docker/develop_init.sh
      NFQ_REMOTE_TOOL_WEB: >
        /usr/bin/gem
        /usr/local/bin/bundle


  linker:
    image: nfqlt/linker17ce
    network_mode: bridge
    volumes:
      - '/run/docker.sock:/run/docker.sock'


volumes: {  }
networks: {  }

