version: '2.1'
services:
  web:
    image: nfqlt/apache24-fastcgi
    network_mode: bridge
    ports:
      - '10.24.1.33:80:80'
    links:
      - fastcgi
    volumes:
      - './src:/home/project/src'
    environment:
      APACHE_DOCUMENTROOT: /home/project/src/public
      NFQ_PROJECT_ROOT: /home/project/src
      NFQ_ENABLE_APACHE_MODULES: rewrite


  fastcgi:
    image: nfqlt/php71-fpm
    network_mode: bridge
    volumes:
      - './src:/home/project/src'
    environment:
      NFQ_PROJECT_ROOT: /home/project/src
      NFQ_ENABLE_PHP_MODULES: 'curl json mcrypt ctype tokenizer simplexml intl mbstring xml zip dom xmlwriter xmlreader iconv xdebug'


  dev:
    image: nfqlt/php71-dev
    network_mode: bridge
    ports:
      - '10.24.1.33:22:22'
    volumes:
      - './src:/home/project/src'
      - '/home/project/.ssh:/home/project/.ssh'
      - '/etc/ssh:/etc/ssh'
      - '/etc/gitconfig:/etc/gitconfig'
      - '/etc/environment:/etc/environment-vm:ro'
      - '/vagrant/bash_custom:/home/project/.bash_custom'
    environment:
      NFQ_ENABLE_PHP_MODULES: 'curl json mcrypt ctype tokenizer simplexml intl mbstring xml zip dom xmlwriter xmlreader iconv xdebug'
      NFQ_PROJECT_ROOT: /home/project/src
      NFQ_PROJECT_GIT_REPO: 'git@github.com:makerspacelt/api.git'
      NFQ_PROJECT_GIT_BRANCH: develop
      NFQ_INIT_SCRIPT: tools/docker/develop_init.sh


  linker:
    image: nfqlt/linker17ce
    network_mode: bridge
    volumes:
      - '/run/docker.sock:/run/docker.sock'


volumes: {  }
networks: {  }

