version: '2.1'
services:
  web:
    image: nfqlt/apache24-fastcgi
    network_mode: bridge
    ports:
      - '80:80'
    links:
      - fastcgi
    volumes:
      - './src:/home/project/src'
    environment:
      APACHE_DOCUMENTROOT: /home/project/src/public
      NFQ_PROJECT_ROOT: /home/project/src
      NFQ_ENABLE_APACHE_MODULES: rewrite


  fastcgi:
    image: nfqlt/php71-fpm
    network_mode: bridge
    volumes:
      - './src:/home/project/src'
    environment:
      NFQ_PROJECT_ROOT: /home/project/src
      NFQ_ENABLE_PHP_MODULES: 'curl json mcrypt ctype tokenizer simplexml intl mbstring xml zip dom xmlwriter xmlreader iconv'


  dev:
    image: nfqlt/php71-dev
    network_mode: bridge
    volumes:
      - './src:/home/project/src'
      - './ssh:/home/project/.ssh'
      - './conf.d/symfony-env:/home/project/.env:ro'
    environment:
      NFQ_ENABLE_PHP_MODULES: 'curl json mcrypt ctype tokenizer simplexml intl mbstring xml zip dom xmlwriter xmlreader iconv'
      NFQ_PROJECT_ROOT: /home/project/src
      NFQ_PROJECT_GIT_REPO: 'https://github.com/makerspacelt/acs.git'
      NFQ_PROJECT_GIT_BRANCH: master
      NFQ_INIT_SCRIPT: tools/docker/prod_init.sh


  linker:
    image: nfqlt/linker17ce
    network_mode: bridge
    volumes:
      - '/run/docker.sock:/run/docker.sock'


volumes: {  }
networks: {  }

